myproject/Outstanding/views.py
from flask import Blueprint, render_template, url_for, redirect, session
from myproject.missinglines.forms import datefilter
from myproject.models import con_sql
from datetime import datetime

bp_otsd = Blueprint('outstanding',__name__,template_folder='templates/claim')


@bp_otsd.route('/', methods=['GET','POST'])
def claim():
    form = datefilter()

    sql1 = """
        SELECT *
        FROM DB2
        WHERE VAR1 > 0
            AND ....        
    """
    sql2 = """GROUP BY VAR5 ORDER BY 1"""
    global alist
    if form.validate_on_submit():
        conn = con_sql().consql
        cur = conn.cursor()
        session['sdate'] = datetime.strftime(form.sdate3.data,'%Y-%m-%d')
        qsdate = "'" + session['sdate'] + "'"
        session['edate'] = edate = datetime.strftime(form.edate.data,'%Y-%m-%d')
        qedate = "'" + session['edate'] + "'"

        joinsql = f"""AND VAR7 >= {qsdate} AND VAR7 <= {qedate}"""

        statement = sql1 + joinsql +sql2
        cur.execute(statement)
        alist = cur.fetchall()

        return redirect(url_for('claim_results', alist=alist))
    return render_template('claim.html', form=form)

@bp_otsd.route('/claim_results')
def claim_results():
    global allist
    return render_template('claim_results.html', alist=alist)

myproject/templates/base.html
{# base HTML #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finance</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand " href="{{ url_for('index') }}">Home</a>
        <a class="nav-link text-light font-weight-light" href="{{ url_for('helppage') }}">Help</a>
    </nav>
    {% block content %}
    {% endblock %}

</body>
</html>

myproject/templates/helppage.html
{% extends "base.html" %}

{% block content%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Oops!</strong> You have reached the help page but <strong>no help below</strong> &#128540;
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>

</div>
{% endblock %}

myproject/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h2>Welcome &#x1F60A;</h2>
</div>
<div>
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td><a href="{{url_for('ReportX.reportx')}}">Report X</a></td>
            <td><a href="{{url_for('ReportY.reporty')}}">Report Y (Download Batches)</a></td>
            <td>Placeholder</td>

        </tr>
            <td><a href="{{url_for('outstanding.claim')}}">Outstanding Claims</a></td>
            <td><a href="{{url_for('reb_process.reb_process')}}">Process Rebates</a></td>
            <td>To be continued...</td>
        <tr>
            <td>To be continued...</td>
        </tr>
        </tbody>
    </table>
</div>

{% endblock %}